name: plaidml_env
channels:
  - defaults
dependencies:
  - hdf5=1.10.2
  - opencv=3.4.2
  - pandas=0.25.2
  - pillow=6.2.0
  - python=3.6
  - pyqt=5.9.2
  - qt=5.9.7
  - h5py=2.8
  - tensorflow=1.13
  - keras=2.2.4
  - pip:
    - numpy==1.17.3
    - plaidml-keras==0.6.4
    - plaidbench